### ISSUE TITLE
Crashing on first request after enabling barnes

### ISSUE THREAD

**Issue by ricardovj** [heroku/barnes#22]
Hey guys, as soon as I add the `barnes` gem and configure/start it in the `before_fork` hook as instructed, my API launches OK but on first request it crashes with [this crash report](https://gist.github.com/ricardovj/0708ad984af5bef570fc279a9869ec39). Any ideas?

**Comment by schneems** [comment]
The segfault wouldn't directly be caused by barnes. It looks like an issue in one of your native extensions. Also you're running an older version of Ruby. I suggest upgrading to at least 2.4.5.

Here's an article on how to inspect which of your native extensions are installed https://devcenter.heroku.com/articles/ruby-segfault. As a good first step upgrade them all to the latest reasonable version.

**Comment by ricardovj** [comment]
Cool, thanks, I'll check that out. Question is why that would only happen after adding barnes? Without it everything works just fine 🤔

**Comment by ricardovj** [comment]
Upgrading to 2.6 fixed the problem, thanks!
